### ISSUE TITLE
Stop script when window closes

### ISSUE THREAD

**Issue by Valmontechno** [ZetaMap/Ion-numworks#2]
Closing the Kandinsky window should interrupt the execution of the program because otherwise it may never stop or return an `kandinsky window destroyed` error.

**Comment by ZetaMap** [comment]
I thing no, the programmer should handle it, because when you press the back or home button, this raise an KeyboardInterrupt error.
But I found a bug with Ion, when you want to stop the script, it never stops because of the keyboard listener, which is always running

**Comment by ZetaMap** [comment]
And also the error "Kandinsky window destroyed" is raised into an KeyboardInterrupt error, and the definition of this error is to stop the program when you press CTRL+C or when you raise it
