### ISSUE TITLE
Can't install package with pycharm

### ISSUE THREAD

**Issue by MaledictYtb** [ZetaMap/Ion-numworks#4]
Bonjour, j'ai un petit soucis. Lorsque je veux installer ion-numworks directement dans pycharm, j'ai cette erreur et ça ne s'installe pas. 

J'arrive pourtant à installer le package en suivant ce guide : https://www.jetbrains.com/help/pycharm/package-installation-issues.html#terminal

Collecting ion-numworks==2.0.dev4
  Using cached ion_numworks-2.0.dev4-py3-none-any.whl.metadata (7.0 kB)
Collecting pynput (from ion-numworks==2.0.dev4)
  Using cached pynput-1.7.6-py2.py3-none-any.whl.metadata (30 kB)
Collecting six (from pynput->ion-numworks==2.0.dev4)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting evdev>=1.3 (from pynput->ion-numworks==2.0.dev4)
  Using cached evdev-1.7.0.tar.gz (30 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting python-xlib>=0.17 (from pynput->ion-numworks==2.0.dev4)
  Using cached python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Using cached ion_numworks-2.0.dev4-py3-none-any.whl (18 kB)
Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: evdev
  Building wheel for evdev (pyproject.toml): started
  Building wheel for evdev (pyproject.toml): finished with status 'error'
Failed to build evdev

  error: subprocess-exited-with-error
  
  × Building wheel for evdev (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/__init__.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/device.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/ecodes.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/eventio.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/eventio_async.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/events.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/evtest.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/ff.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/genecodes.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/uinput.py -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/util.py -> build/lib.linux-x86_64-cpython-312/evdev
      running egg_info
      writing evdev.egg-info/PKG-INFO
      writing dependency_links to evdev.egg-info/dependency_links.txt
      writing top-level names to evdev.egg-info/top_level.txt
      reading manifest file 'evdev.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'evdev/ecodes.c'
      adding license file 'LICENSE'
      writing manifest file 'evdev.egg-info/SOURCES.txt'
      copying evdev/input.c -> build/lib.linux-x86_64-cpython-312/evdev
      copying evdev/uinput.c -> build/lib.linux-x86_64-cpython-312/evdev
      running build_ext
      running build_ecodes
      The 'linux/input.h' and 'linux/input-event-codes.h' include files
      are missing. You will have to install the kernel header files in
      order to continue:
      
          dnf install kernel-headers-$(uname -r)
          apt-get install linux-headers-$(uname -r)
          emerge sys-kernel/linux-headers
          pacman -S kernel-headers
      
      In case they are installed in a non-standard location, you may use
      the '--evdev-headers' option to specify one or more colon-separated
      paths. For example:
      
          python setup.py \
            build \
            build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
            build_ext --include-dirs path/ \
            install
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for evdev
ERROR: Could not build wheels for evdev, which is required to install pyproject.toml-based projects

**Comment by ZetaMap** [comment]
Rien de grave, seulement quelques librairies manquantes pour evdev. Dans l'erreur, il te donne la commande pour installer les headers linux

**Comment by MaledictYtb** [comment]
Ce qui est étrange c'est que ça marche dans un terminal en dehors de pycharm. Pourquoi est-ce que pycharm n'y arrive pas alors ?

**Comment by ZetaMap** [comment]
Car PyCharm est un IDE qui exécute tout dans un environnement virtuel, comme le spécifient les nouvelles recommandations de Python, mais surtout en général, c'est ce qu'il a toujours fait.

J'ai essayé de faire fonctionner la librairie dedans, mais ça ne marche tout simplement pas. Il ne peut pas accéder aux entrées clavier.

Pour cela, je ne pourrais rien faire, cela relève de PyCharm eux-mêmes, ou de la configuration de l'IDE. Je n'en sais pas plus, je ne l'utilise pas.

**Comment by MaledictYtb** [comment]
Ok, tant pis, on peut toujours l'installer à la main.
